lints.workspace = true

[package]
name = "defuse-near-utils"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
borsh = { workspace = true, features = ["derive"], optional = true }
impl-tools.workspace = true
near-sdk.workspace = true

[features]
abi = ["borsh-schema"]
borsh = ["dep:borsh"]
borsh-schema = ["borsh", "borsh/unstable__schema"]

[dev-dependencies]
defuse-test-utils.workspace = true

near-sdk = { workspace = true, features = ["unit-testing"] }
rstest.workspace = true
