lints.workspace = true

[package]
name = "defuse-mpc-signer"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-crypto = { workspace = true, features = ["ed25519", "secp256k1", "serde"] }
defuse-kdf = { workspace = true, features = ["ed25519", "secp256k1"] }
defuse-mpc-kdf = { workspace = true, features = ["ed25519", "secp256k1"] }
defuse-near-promise = { workspace = true, features = ["json"] }
defuse-near-sender = { workspace = true, features = ["near-kit"] }

impl-tools.workspace = true
near-kit.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["hex"] }
thiserror.workspace = true
trait-variant.workspace = true
