[package]
name = "defuse-tep104"
version.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
defuse-crypto = { workspace = true, features = ["serde"] }

impl-tools.workspace = true
near-sdk.workspace = true
serde_with.workspace = true
tlb.workspace = true

[features]
abi = ["defuse-crypto/abi"]

[dev-dependencies]
hex-literal.workspace = true
