lints.workspace = true

[package]
name = "defuse-webauthn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-digest = { workspace = true, features = ["sha2"] }
defuse-kdf-crypto.workspace = true

cfg_eval.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["base64"] }

arbitrary = { workspace = true, features = ["derive"], optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }

[features]
abi = ["schemars-v0_8"]
arbitrary = ["dep:arbitrary"]
ed25519 = ["defuse-kdf-crypto/ed25519"]
p256 = ["defuse-kdf-crypto/p256"]
schemars-v0_8 = ["dep:schemars", "serde_with/schemars_0_8"]

[dev-dependencies]
defuse-webauthn = { path = ".", features = ["arbitrary", "ed25519", "p256", "schemars-v0_8"] }
hex-literal.workspace = true
rstest.workspace = true
