services:
  worker:
    image: mat13mn/worker:latest
    environment:
      RUST_LOG: "outlayer=info,defuse_outlayer_service=debug,defuse_outlayer_executor=debug"
      WORKER__ADDR: "0.0.0.0:50051"
      WORKER__CONCURRENCY_LIMIT: 2
      WORKER__CONCURRENCY_LIMIT_PER_CONNECTION: 1
      WORKER__CONNECTIONS_LIMIT: 10
      WORKER__EXECUTION_TIMEOUT_S: 30
      WORKER__SERVICE__CACHE__MAX_CAPACITY_BYTES: 104857600
      WORKER__SERVICE__CACHE__TIME_TO_IDLE: 3600
      WORKER__SERVICE__DEFAULT_FUEL: 1000000000
      WORKER__SERVICE__EXECUTOR__LIMITS__STDERR: 16384
      WORKER__SERVICE__EXECUTOR__LIMITS__STDIN: 4194304
      WORKER__SERVICE__EXECUTOR__LIMITS__STDOUT: 4194304
      WORKER__SERVICE__EXECUTOR__MEMORY_LIMIT: 104857600
      WORKER__SERVICE__RESOLVER__HTTP_MAX_LEN: 10485760
      WORKER__SERVICE__RESOLVER__NEAR_CHAIN_ID: "mainnet"
      WORKER__SERVICE__RESOLVER__NEAR_RPC_URL: "https://rpc.mainnet.near.org"
      WORKER__SIGNER_SEED: ${WORKER__SIGNER_SEED}
    ports:
      - "50051:50051"
