use defuse_core::PublicKey;
use defuse_sandbox::{
    extensions::{
        acl::AccessControllableExt,
        defuse::{DefuseExt, contract::Role},
    },
    kit::{InMemorySigner, KeyPair},
};
use rstest::rstest;

use crate::{
    tests::defuse::env::{Env, env},
    utils::asserts::ResultAssertsExt,
};

#[rstest]
#[tokio::test]
async fn relayer_keys(
    #[with(Env::builder().deployer_as_super_admin())]
    #[future(awt)]
    env: Env,
) {
    let (user, other_user) = futures::join!(env.create_user(), env.create_user());

    env.acl_grant_role(
        env.defuse.contract_id(),
        Role::RelayerKeysManager,
        user.account_id(),
    )
    .await
    .unwrap();

    // We generate a new key, because all keys generated by Near Workspaces are the same
    let new_relayer_signer = KeyPair::random();
    let new_relayer_public_key_near_sdk: PublicKey = new_relayer_signer.public_key.into();
    let new_relayer_signer = env.with_signer(
        InMemorySigner::from_secret_key(
            env.defuse.contract_id().clone(),
            new_relayer_signer.secret_key,
        )
        .unwrap(),
    );

    // Attempt to use the key that we still didn't add, to execute an intent, which fails
    new_relayer_signer
        .defuse_simulate_and_execute_intents(env.defuse.contract_id(), []) // Empty because it's just to ensure that authorization works/doesn't work
        .await
        .unwrap_err();

    // A random, unauthorized user attempts to add a key (no role `Role::RelayerKeysManager`) and fails
    other_user
        .defuse_add_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .assert_err_contains("Requires one of these roles:");

    // A `Role::RelayerKeysManager` attempts to add the key, successfully
    user.defuse_add_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .unwrap();

    // Attempt to add a key that already exists
    user.defuse_add_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .assert_err_contains("key already exists");

    // Create a Function-call Key, then use it to execute an (empty) intent
    new_relayer_signer
        .defuse_simulate_and_execute_intents(env.defuse.contract_id(), []) // Empty because it's just to ensure that authorization works/doesn't work
        .await
        .unwrap();

    // Attempt to delete the key by an unauthorized user
    other_user
        .defuse_delete_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .assert_err_contains("Requires one of these roles:");

    // Delete the relayer key by the authorized entity
    user.defuse_delete_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .unwrap();

    // Delete the same key again, which won't work

    user.defuse_delete_relayer_key(env.defuse.contract_id(), &new_relayer_public_key_near_sdk)
        .await
        .assert_err_contains("key not found");

    let access_keys = env.access_keys(env.defuse.contract_id()).await.unwrap();
    dbg!(&access_keys);
    assert!(!access_keys.keys.is_empty());
}
