lints.workspace = true

[package]
name = "defuse-nep245"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
borsh = { workspace = true, features = ["derive"] }
defuse-near-utils.workspace = true
defuse-serde-utils.workspace = true
derive_more = { workspace = true, features = ["from"] }
near-account-id = { workspace = true, features = ["borsh", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
thiserror.workspace = true

near-sdk = { workspace = true, optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }

[features]
abi = [
  "borsh/unstable__schema",
  "defuse-serde-utils/schemars-v0_8",
  "dep:schemars",
]
near-contract = ["dep:near-sdk"]

[dev-dependencies]
defuse-nep245 = { workspace = true, features = ["near-contract"] }
near-sdk = { workspace = true, features = ["unit-testing"] }
