lints.workspace = true

[package]
name = "defuse-nep245"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-near-utils = { workspace = true, optional = true }
defuse-serde-utils.workspace = true
derive_more = { workspace = true, features = ["from"] }
near-account-id.workspace = true
near-sdk = { workspace = true, optional = true }
serde_with.workspace = true
thiserror.workspace = true

cfg_eval = { workspace = true, optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
abi = ["near-account-id/abi", "near-sdk/abi", "schemars-v0_8"]
near-contract = ["dep:defuse-near-utils", "dep:near-sdk", "serde"]
schemars-v0_8 = [
  "defuse-serde-utils/schemars-v0_8",
  "dep:schemars",
  "near-account-id/schemars-v0_8",
  "serde",
]
serde = ["dep:cfg_eval", "dep:serde", "near-account-id/serde"]

[dev-dependencies]
defuse-nep245 = { workspace = true, features = ["near-contract"] }
near-sdk = { workspace = true, features = ["unit-testing"] }
