[package]
name = "defuse-randomness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
rand = { workspace = true }
