use std::sync::Arc;
use std::time::Duration;

use bytes::Bytes;
use ed25519_dalek::{Signature, SigningKey};
use serde::{Deserialize, Serialize};
use serde_with::{hex::Hex, serde_as};
use thiserror::Error;
use uuid::Uuid;
use wasmtime::component::Component;

/// Opaque NEAR account identifier. Wraps a validated string.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AccountId(pub String);

impl std::fmt::Display for AccountId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// All data carried by an on-chain execution request.
#[serde_as]
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize)]
pub struct OnChainRequest {
    /// Unique request ID generated by the caller.
    pub id: Uuid,
    /// Transaction hash that originated this request on-chain.
    #[serde_as(as = "Hex")]
    pub tx_hash: [u8; 32],
    pub project_id: AccountId,
    #[serde_as(as = "serde_with::base64::Base64")]
    pub input: Bytes,
    #[serde_as(as = "Hex")]
    pub wasm_hash: [u8; 32],
    /// URL to fetch the WASM binary from.
    pub wasm_url: String,
}

/// Worker-controlled resource caps. Never caller-controlled.
#[derive(Debug, Clone, Default)]
pub struct ResourceLimits;

/// Placeholder for on-chain project storage (key → value snapshot).
#[derive(Debug, Clone, Default, Serialize)]
pub struct ProjectStorage;

/// Placeholder for decrypted project environment variables / secrets.
#[derive(Debug, Clone, Default)]
pub struct ProjectEnv;

/// Fully normalised execution request consumed by the inner Tower stack.
/// All inputs are resolved; WASM is already compiled.
#[derive(Clone)]
pub struct WasmExecutionRequest {
    pub request: OnChainRequest,
    pub component: Component,
    pub storage: ProjectStorage,
    pub env: ProjectEnv,
    pub caller: Option<AccountId>,
    pub limits: ResourceLimits,
}

/// Target NEAR contract for submitting the execution response.
#[derive(Debug, Clone, Serialize)]
pub struct OnChainDestination {
    pub contract_id: AccountId,
}

#[derive(Debug, Default, Serialize)]
pub struct ExecutionMetrics {
    pub instructions_used: u64,
    // wall_time and compile_time excluded from signature payload
    #[serde(skip)]
    pub wall_time: Duration,
    #[serde(skip)]
    pub compile_time: Option<Duration>,
}

/// WASM-level execution failure stored in `ExecutionResponse::result`.
#[derive(Debug, Error, Serialize)]
pub enum ExecutionError {
    #[error("resource limit exceeded")]
    ResourceLimit,
    #[error("wasm trap: {0}")]
    Trap(String),
    #[error("storage error: {0}")]
    Storage(String),
}

/// Raw output from `WasmExecutor`. Signed via `map_response(sign)` before
/// leaving the stack.
#[derive(Debug, Serialize)]
pub struct ExecutionResponse {
    /// Copied from `OnChainRequest::id` — ties the response to its request
    /// and ensures each signed response is unique even for identical content.
    pub request_id: Uuid,
    /// Raw stdout, capped at `limits.max_output_bytes`. Caller decodes.
    pub result: Result<Bytes, ExecutionError>,
    pub metrics: ExecutionMetrics,
    /// Storage state after execution, to be submitted on-chain by the caller.
    pub storage: ProjectStorage,
    pub respond_to: OnChainDestination,
}

/// `ExecutionResponse` after signing. The type guarantees the signature is
/// present — there is no intermediate state where `signature` is uninitialised.
#[derive(Debug)]
pub struct SignedExecutionResponse {
    pub response: ExecutionResponse,
    /// Worker ed25519 signature over the JSON-serialised `ExecutionResponse`.
    pub signature: Signature,
}

/// Worker's ed25519 signing key, cheaply cloneable via `Arc`.
#[derive(Clone)]
pub struct WorkerSigningKey(pub Arc<SigningKey>);

impl WorkerSigningKey {
    pub fn sign(&self, response: ExecutionResponse) -> SignedExecutionResponse {
        use ed25519_dalek::Signer;
        let payload =
            serde_json::to_vec(&response).expect("ExecutionResponse serialization is infallible");
        let signature = self.0.sign(&payload);
        SignedExecutionResponse { response, signature }
    }
}

// ── Network-facing request types ─────────────────────────────────────────────

/// Cryptographic proof that `caller` controls the stated NEAR account.
#[serde_as]
#[derive(Debug, Clone, Deserialize)]
pub struct IdentityProof {
    #[serde_as(as = "Hex")]
    pub public_key: [u8; 32],
    #[serde_as(as = "Hex")]
    pub signature: [u8; 64],
}

/// Network-facing execution request.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Request {
    OnChain(OnChainRequest),
    /// Placeholder — offchain request format TBD.
    OffChain,
}
