lints.workspace = true

[package]
name = "defuse-wallet-webauthn"
edition.workspace = true
version = "0.1.0"
rust-version.workspace = true
repository.workspace = true
readme = "../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
defuse-kdf-crypto = { workspace = true, features = ["serde"] }
defuse-wallet-core = { workspace = true, features = ["serde"] }
defuse-webauthn.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

arbitrary = { workspace = true, features = ["derive"], optional = true }
borsh = { workspace = true, features = ["derive"], optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }

[features]
ed25519 = ["defuse-kdf-crypto/ed25519"]
p256 = ["defuse-kdf-crypto/p256"]

abi = [
  "borsh-schema",
  "defuse-kdf-crypto/abi",
  "defuse-wallet-core/abi",
  "schemars-v0_8",
]
arbitrary = [
  "defuse-kdf-crypto/arbitrary",
  "defuse-wallet-core/arbitrary",
  "defuse-webauthn/arbitrary",
  "dep:arbitrary",
]
borsh = [
  "defuse-kdf-crypto/borsh",
  "defuse-wallet-core/borsh",
  "defuse-webauthn/borsh",
  "dep:borsh",
]
borsh-schema = [
  "borsh",
  "borsh?/unstable__schema",
  "defuse-kdf-crypto/borsh-schema",
  "defuse-wallet-core/borsh-schema",
  "defuse-webauthn/borsh-schema",
]
schemars-v0_8 = [
  "defuse-kdf-crypto/schemars-v0_8",
  "defuse-wallet-core/schemars-v0_8",
  "defuse-webauthn/schemars-v0_8",
  "dep:schemars",
]

near-contract = ["defuse-wallet-core/near-contract"]

[dev-dependencies]
defuse-wallet-webauthn = { path = ".", features = ["abi", "near-contract", "ed25519", "p256"] }

hex-literal.workspace = true
rstest.workspace = true
