[package]
name = "defuse-borsh-utils"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
defuse-io-utils.workspace = true

near-sdk.workspace = true
impl-tools.workspace = true
