[package]
name = "defuse-borsh-utils"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
defuse-io-utils.workspace = true

near-sdk.workspace = true
impl-tools.workspace = true
