[package]
name = "wtoken"
version = "0.1.0"
edition.workspace = true
repository.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
defuse-admin-utils.workspace = true
defuse-near-utils.workspace = true

near-sdk = "5.5.0"
near-contract-standards = "5.5.0"

[dev-dependencies]
near-sdk = { version = "5.5.0", features = ["unit-testing"] }
near-workspaces = { version = "0.14.1", features = ["unstable"] }
anyhow = "1.0"
tokio = { version = "1.41.0", features = ["full"] }
cargo-near-build = "0.3.2"

[lints]
workspace = true

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
