[package]
name = "defuse-bip322"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
defuse-crypto = { workspace = true, features = ["serde"] }
defuse-near-utils.workspace = true

near-sdk.workspace = true
serde_with.workspace = true

[features]
abi = ["defuse-crypto/abi"]

[dev-dependencies]
hex-literal.workspace = true
near-sdk = { workspace = true, features = ["unit-testing"] }
rstest.workspace = true
