lints.workspace = true

[package]
name = "defuse-wallet-ed25519"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-crypto = { workspace = true, features = ["ed25519"] }
defuse-wallet-core.workspace = true

[dev-dependencies]
hex-literal.workspace = true
rstest.workspace = true
