[package]
name = "defuse-escrow1"
edition.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
defuse-nep245.workspace = true
defuse-token-id.workspace = true

near-contract-standards.workspace = true
near-sdk.workspace = true

chrono.workspace = true

[features]
contract = []
