lints.workspace = true

[package]
# TODO: rename to verifier
name = "defuse-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-bitmap = { workspace = true, features = ["borsh"] }
defuse-crypto = { workspace = true, features = ["borsh", "ed25519", "secp256k1", "p256", "serde"] }
defuse-digest = { workspace = true, features = ["sha2"] }
defuse-erc191.workspace = true
defuse-fees = { workspace = true, features = ["borsh", "serde"] }
defuse-map-utils.workspace = true
defuse-nep245.workspace = true
defuse-nep413 = { workspace = true, features = ["serde"] }
defuse-num-utils.workspace = true
defuse-sep53.workspace = true
# defuse-signature-schema.workspace = true
defuse-time = { workspace = true, features = ["borsh", "serde"] }
defuse-tip191.workspace = true
defuse-token-id = { workspace = true, features = ["borsh", "serde"] }
defuse-ton-connect = { workspace = true, features = ["serde"] }
defuse-webauthn = { workspace = true, features = ["ed25519", "p256"] }

borsh = { workspace = true, features = ["derive"] }
defuse-borsh-utils.workspace = true
derive_more = { workspace = true, features = ["from"] }
hex.workspace = true
hex-literal.workspace = true
impl-tools.workspace = true
near-account-id = { workspace = true, features = ["borsh", "serde"] }
near-gas = { workspace = true, features = ["borsh", "serde"] }
near-global-contracts = { workspace = true, features = ["borsh", "serde"] }
near-token = { workspace = true, features = ["borsh", "serde"] }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["base58", "base64"] }
thiserror.workspace = true

arbitrary = { workspace = true, features = ["derive"], optional = true }
base64 = { workspace = true, optional = true }
near-kit = { workspace = true, optional = true }
near-sdk = { workspace = true, optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }

[features]
abi = ["borsh-schema", "schemars-v0_8"]
arbitrary = [
  "defuse-bitmap/arbitrary",
  "defuse-crypto/arbitrary",
  "defuse-token-id/arbitrary",
  "defuse-ton-connect/arbitrary",
  "dep:arbitrary",
  "near-account-id/arbitrary",
  "near-gas/arbitrary",
  "near-global-contracts/arbitrary",
  "near-token/arbitrary",
]
borsh-schema = [
  "borsh/unstable__schema",
  "defuse-bitmap/borsh-schema",
  "defuse-crypto/borsh-schema",
  "defuse-fees/borsh-schema",
  "defuse-nep413/borsh-schema",
  "defuse-time/borsh-schema",
  "defuse-token-id/abi",
  "defuse-webauthn/borsh-schema",
  "near-account-id/abi",
  "near-gas/abi",
  "near-global-contracts/abi",
  "near-token/abi",
]
imt = []
near-kit = ["defuse-nep413/near-kit", "dep:near-kit"]
near-contract = ["defuse-nep245/near-contract", "dep:near-sdk"]
schemars-v0_8 = [
  "base64",
  "defuse-crypto/schemars-v0_8",
  "defuse-fees/schemars-v0_8",
  "defuse-nep245/schemars-v0_8",
  "defuse-nep413/schemars-v0_8",
  "defuse-time/schemars-v0_8",
  "defuse-token-id/abi",
  "defuse-ton-connect/schemars-v0_8",
  "defuse-webauthn/schemars-v0_8",
  "dep:schemars",
  "near-gas/schemars",
  "near-global-contracts/schemars-v0_8",
  "near-token/schemars",
  "serde_with/schemars_0_8",
  "near-account-id/schemars-v0_8"
]

[dev-dependencies]
defuse-core = { workspace = true, features = ["arbitrary"] }
defuse-test-utils.workspace = true

bs58.workspace = true
hex-literal.workspace = true
itertools.workspace = true
near-sdk = { workspace = true, features = ["unit-testing"] }
rstest.workspace = true
