lints.workspace = true

[package]
name = "defuse-wallet-sdk"
edition.workspace = true
version = "0.1.0"
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-wallet = { workspace = true, features = ["borsh", "digest"] }

async-trait.workspace = true
borsh.workspace = true
impl-tools.workspace = true
near-global-contracts = { workspace = true, features = ["borsh"] }
rand.workspace = true

[features]
json = ["defuse-wallet/json"]
