lints.workspace = true

[package]
name = "defuse-wallet-sdk"
edition.workspace = true
version = "0.1.0"
rust-version.workspace = true
repository.workspace = true

[dependencies]
defuse-wallet = { workspace = true, features = ["borsh", "digest", "json", "serde"] }

async-trait.workspace = true
borsh.workspace = true
impl-tools.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
trait-variant.workspace = true

bs58 = { workspace = true, optional = true }
defuse-mpc-signer = { workspace = true, optional = true }
defuse-near-sender = { workspace = true, features = ["serde"], optional = true }
derive_more = { workspace = true, features = ["from"], optional = true }
near-kit = { workspace = true, default-features = false, optional = true }
schemars = { workspace = true, features = ["derive"], optional = true }
thiserror = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[features]
default = ["mpc", "near-kit", "relayer"] # TODO: add more?

near-kit = [
  "defuse-near-sender?/near-kit",
  "defuse-wallet/near-kit",
  "dep:derive_more",
  "dep:near-kit",
]
mpc = ["dep:defuse-mpc-signer", "relayer"]
relayer = ["dep:defuse-near-sender", "dep:thiserror"]
schemars-v0_8 = [
  "defuse-near-sender?/schemars-v0_8",
  "defuse-wallet/schemars-v0_8",
  "dep:schemars",
]
tracing = ["dep:bs58", "dep:tracing"]

[dev-dependencies]
defuse-wallet-sdk = { path = ".", features = ["near-kit", "relayer", "mpc"] }

defuse-wallet-ed25519 = { workspace = true, features = ["signer"] }
near-kit = { workspace = true, features = ["sandbox"] }
rand = { workspace = true, features = ["sys_rng"] }
rstest.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
