lints.workspace = true

[package]
name = "defuse-kdf-crypto"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
ed25519-dalek = { workspace = true, features = ["std"], optional = true }
k256 = { workspace = true, features = ["std", "arithmetic", "ecdsa"], optional = true }

[target.'cfg(near)'.dependencies]
near-sdk = { workspace = true, optional = true }

[features]
ed25519 = ["dep:ed25519-dalek", "dep:near-sdk"]
secp256k1 = ["dep:k256", "dep:near-sdk", "near-sdk/unstable"]

[dev-dependencies]
ed25519-dalek = { workspace = true, features = ["std", "serde"] }
hex-literal.workspace = true
k256 = { workspace = true, features = ["std", "arithmetic", "ecdsa"] }
rstest.workspace = true

[target.'cfg(near)'.dev-dependencies]
near-sdk = { workspace = true, features = ["unit-testing"] }
