name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  EXEC: nix develop --command

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Check formatting
        run: $EXEC make check-fmt

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Run clippy for workspace
        run: $EXEC make check
      - name: Check for unused dependencies
        run: $EXEC make check-unused-deps

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Build
        run: $EXEC make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: res
          path: ./res/

  build-reproducible:
    name: Build Reproducible
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Build reproducible WASM
        run: $EXEC make REPRODUCIBLE=1
      - name: Upload reproducible artifacts
        uses: actions/upload-artifact@v4
        with:
          name: res_reproducible
          path: ./res/
          compression-level: 0

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-reproducible
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Download reproducible artifacts
        uses: actions/download-artifact@v4
        with:
          name: res_reproducible
          path: ./res
      - name: Run tests
        env:
          DEFUSE_MIGRATE_FROM_LEGACY: "true"
          DEFUSE_USE_OUT_DIR: res
        run: $EXEC make test

  security-audit-report:
    name: Security Audit - report
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Run audit report
        run: $EXEC cargo audit

  security-audit-deny:
    name: Security Audit - deny
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Run security audit
        run: $EXEC cargo audit --deny unsound --deny yanked
